export const TODAY_FETCH = "TODAY_FETCH";
export const TODAY_SUCCESS = "TODAY_SUCCESS";
export const TODAY_FAILURE = "TODAY_FAILURE";
export const FORECAST_FETCH = "FORECAST_FETCH";
export const FORECAST_SUCCESS = "FORECAST_SUCCESS";
export const FORECAST_FAILURE = "FORECAST_FAILURE";
export const SELECT_CITY = "SELECT_CITY";
